NumPy = Numerical Python
Used for:
- Fast numerical computation
- Statistics, linear algebra, ML preprocessing
- Working with arrays, vectors, matrices

In [15]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)

# 2D Arr
b = np.array([[2,3], [78,88]])
print(b)

# 3D array
c = np.array([[2,3], [78,88], [12,22]])
print(c)

# Array Properrties

c.shape
c.ndim      # number of dimensions
c.size      # total elements
c.dtype     # data type

[1 2 3 4]
[[ 2  3]
 [78 88]]
[[ 2  3]
 [78 88]
 [12 22]]


dtype('int64')